#!/usr/bin/env rake
require 'rake/clean'

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new('spec')

task :export_to_docker do
  branch_name = `git branch | grep \\* | cut -d ' ' -f2`
  `git archive #{branch_name.chomp} -o ../pkg/repo.tar.gz`
end

task :perform_tests => [:spec, :rubocop]
task :default => :perform_tests

