#!/usr/bin/env rake
require 'rake/clean'
require 'knapsack'

require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new('spec')

task :export_to_docker do
  `bin/create_git_archive.sh`
end


Knapsack.load_tasks if defined?(Knapsack)


